---
title: "coagglomeration -- interplots"
output: html_notebook
---

by sandorjuhasz

### coagglomeration

setting info



```{r, echo=FALSE, results=FALSE, message=FALSE}
library(data.table)
library(dplyr)
library(stargazer)
library(ivreg)
library(lmtest)
library(sandwich)
library(interplot)
library(cowplot)
source("../code/05a_regression_functions.R")

# parameters
focal_year <- 2017
#region_level <- "nuts3"
region_level <- "nuts4"
#region_level <- "city"
version <- ""

```





```{r, echo=FALSE, warning=FALSE}
fontsize <- 10
region_codes <- c("nuts4")
model_version <- c("noFE", "FE")
path <- paste0("../data/oc15_2023_dec/04oc_data_", version, region_codes, "_", focal_year, ".csv")
reg_df <- prep_baseline_regression_table(path)
#reg_df <- reg_df[complete.cases(reg_df[ , c("io_norm2")]), ]


# the model -- EGK
int_egk <- lm(egk_coagg_stand ~ io_wiot_hun * sr_norm, data = reg_df)

ip_a <- interplot(m = int_egk,
                 var1 = "sr_norm",
                 var2 = "io_wiot_hun",
                 #var2 = "io_norm3",
                 size = 3,
                 xmin = -1,
                 xmax = 1,
                 rfill = "#6da3d0") +
  xlab("IO connections") +
  ylab("Estimated coefficient for\nlabor flow") +
  ylim(-0.025, 0.35) +
  geom_hline(yintercept = 0, linetype = "dashed", size=1.5) +
  theme_cowplot(12) +
  theme(axis.text = element_text(size=fontsize-5), axis.title=element_text(size=fontsize))
  #theme(plot.margin = unit(c(2, 1, 0, 1), "cm"))

ip_b <- interplot(m = int_egk,
                 var1 = "io_wiot_hun",
                 #var1 = "io_norm3",
                 var2 = "sr_norm",
                 size = 3,
                 xmin = -1,
                 xmax = 1,
                 rfill = "#6da3d0") +
  xlab("Labor flow") +
  ylab("Estimated coefficient for\nIO connections") +
  ylim(-0.025, 0.35) +
  geom_hline(yintercept = 0, linetype = "dashed", size=1.5) +
  theme_cowplot(12) +
  theme(axis.text = element_text(size=fontsize-5), axis.title=element_text(size=fontsize))
  #theme(plot.margin = unit(c(2, 1, 0, 1), "cm"))


# the model -- LC (emp)
int_pemp <- lm(coagg_porter_emp_stand ~ io_wiot_hun * sr_norm, data = reg_df)

ip_c <- interplot(m = int_pemp,
                  var1 = "sr_norm",
                  var2 = "io_wiot_hun",
                  #var2 = "io_norm3",
                  size = 3,
                  xmin = -1,
                  xmax = 1,
                  rfill = "#6da3d0") +
  xlab("IO connections") +
  ylab("Estimated coefficient for\nlabor flow") +
  ylim(0, 0.7) +
  geom_hline(yintercept = 0, linetype = "dashed", size=1.5) +
  theme_cowplot(12) +
  theme(axis.text = element_text(size=fontsize-5), axis.title=element_text(size=fontsize))
  #theme(plot.margin = unit(c(2, 1.5, 0, 1), "cm"))

ip_d <- interplot(m = int_pemp,
                  var1 = "io_wiot_hun",
                  #var1 = "io_norm3",
                  var2 = "sr_norm",
                  size = 3,
                  xmin = -1,
                  xmax = 1,
                  rfill = "#6da3d0") +
  xlab("Labor flow") +
  ylab("Estimated coefficient for\nIO connections") +
  ylim(0, 0.7) +
  geom_hline(yintercept = 0, linetype = "dashed", size=1.5) +
  theme_cowplot(12) +
  theme(axis.text = element_text(size=fontsize-5), axis.title=element_text(size=fontsize))
  #theme(plot.margin = unit(c(2, 1.5, 0, 1), "cm"))


# combined version
#title <- paste0("mf02_interplots_", model_version[1])
#file_name <- paste0("../figures/", title, "_", region_codes, ".png")
#png(file_name, width=1000, height=700, units = 'px')
plot_grid(
  ip_a, ip_b, ip_c, ip_d
  #labels = c("A", "B", "C", "D"), label_size = fontsize, ncol = 2
)
```

