---
title: "Creating QA networks: SWE labour mobility; HUN national input-output; SWE national input-output"
output:
  html_document:
    css: "../03_scripts/assets/style.css"
    df_print: paged
    number_sections: TRUE
    toc: TRUE
    toc_float: TRUE
    toc_depth: 6
---

# **Setup**

```{r, include = FALSE, echo = FALSE}
#load packages
library(tidyverse)
library(readxl)


#set working directory
path <- "d:/_Hellforge/Vanguard/Operations/Papers/bnet_structure/03_scripts"
setwd(path)


#load functions (default location is project_folder/03_scripts/assets/)
path <- "assets/fenris_funs.R"
source(path)


#Suppress summarise info
options(dplyr.summarise.inform = FALSE)


#Suppress scientific notations
options(scipen = 999)
```





# **General datawork**

```{r}
# load raw labour flow data for 3-digit industries
path <- "../02_data/source/lflow_elist_220511.RData"
load(path)



# load raw labour flow data for 4-digit industries
path <- "../02_data/source/lflow_elist_ind4_220518.RData"
load(path)



# load raw national IO data for HUN
path <- "../02_data/raw_io_table_hun.xlsx"
raw_io_data_hun <- read_xlsx(path)



# load raw national IO data for SWE
path <- "../02_data/raw_io_table_swe.xlsx"
raw_io_data_swe <- read_xlsx(path, sheet = "2016")
```





# **Labour flow networks**

## **Obtain the raw directed SR network from national labour flows between 2013-2019**

```{r, echo = FALSE}
# produce raw SR network from national flows across 2013-2019, 2-digit industries
srnet2dig <-
  lflow_elist %>%
  #set period
  filter(start_year %in% c(2013:2018)) %>%
  #extract REG and IND info
  mutate(
    fareg_i = as.numeric(substr(indreg_i, start = 1, stop = 2)),
    fareg_j = as.numeric(substr(indreg_j, start = 1, stop = 2)),
    ind_i = as.numeric(substr(indreg_i, start = 3, stop = 5)),
    ind_j = as.numeric(substr(indreg_j, start = 3, stop = 5))
  ) %>%
  #aggregate to 2-digit industry level
  mutate(
    ind_i = ind_i %/% 10,
    ind_j = ind_j %/% 10
  ) %>%
  #exclude flows within industry
  filter(ind_i != ind_j) %>%
  select(start_year, ind_i, ind_j, f_ij) %>%
  #obtain aggregate flows across period and region %>%
  group_by(ind_i, ind_j) %>%
  summarise(f_ij = sum(f_ij)) %>%
  ungroup() %>%
  #get SR network
  group_by(ind_i) %>%
	mutate(f_i = sum(f_ij)) %>%
  group_by(ind_j) %>%
  mutate(f_j = sum(f_ij)) %>%
	ungroup() %>%
	mutate(f = sum(f_ij)) %>%
	mutate(sr = f_ij / ((f_i * f_j) / f)) %>%
	mutate(sr_norm = (sr - 1) / (sr + 1))
```

```{r, echo = FALSE}
# produce raw SR network from national flows across 2013-2019, 3-digit industries
srnet3dig <-
  lflow_elist %>%
  #set period
  filter(start_year %in% c(2013:2018)) %>%
  #extract REG and IND info
  mutate(
    fareg_i = as.numeric(substr(indreg_i, start = 1, stop = 2)),
    fareg_j = as.numeric(substr(indreg_j, start = 1, stop = 2)),
    ind_i = as.numeric(substr(indreg_i, start = 3, stop = 5)),
    ind_j = as.numeric(substr(indreg_j, start = 3, stop = 5))
  ) %>%
  #exclude flows within industry
  filter(ind_i != ind_j) %>%
  select(start_year, ind_i, ind_j, f_ij) %>%
  #obtain aggregate flows across period and region %>%
  group_by(ind_i, ind_j) %>%
  summarise(f_ij = sum(f_ij)) %>%
  ungroup() %>%
  #get SR network
  group_by(ind_i) %>%
	mutate(f_i = sum(f_ij)) %>%
  group_by(ind_j) %>%
  mutate(f_j = sum(f_ij)) %>%
	ungroup() %>%
	mutate(f = sum(f_ij)) %>%
	mutate(sr = f_ij / ((f_i * f_j) / f)) %>%
	mutate(sr_norm = (sr - 1) / (sr + 1))
```

```{r, echo = FALSE}
# produce raw SR network from national flows across 2013-2019, 4-digit industries
srnet4dig <-
  lflow_elist_ind4 %>%
  #set period
  filter(start_year %in% c(2013:2018)) %>%
  #exclude flows within industry
  filter(ind_i != ind_j) %>%
  select(start_year, ind_i, ind_j, f_ij) %>%
  #obtain aggregate flows across period and region %>%
  group_by(ind_i, ind_j) %>%
  summarise(f_ij = sum(f_ij)) %>%
  ungroup() %>%
  #get SR network
  group_by(ind_i) %>%
	mutate(f_i = sum(f_ij)) %>%
  group_by(ind_j) %>%
  mutate(f_j = sum(f_ij)) %>%
	ungroup() %>%
	mutate(f = sum(f_ij)) %>%
	mutate(sr = f_ij / ((f_i * f_j) / f)) %>%
	mutate(sr_norm = (sr - 1) / (sr + 1))
```






## **Make SR network undirected and filtered for significant edges**

### **Define functions**

```{r, echo = FALSE}
### get_nlist_frame() ###
# Aim: get a complete nodelist as dataframe based on all nodes present in an edgelist.
# Requires: edgelist with node IDs in the first and second columns.

get_nlist_frame <- function(elist_df){
	
	node_vect <- unique(c(pull(elist_df[, 1]), pull(elist_df[, 2])))
	nlist_df <- data.frame(node_vect)
	colnames(nlist_df) <- "node"
	
	return(nlist_df)
	
}





### get_elist_frame() ###
# Aim: get a complete edgelist, including loops as dataframe based on complete nodelist.
# Requires: nodelist with node IDs in first column (nodelist_frame).

get_elist_frame <- function(nlist_frame_df){
	
	nlist_frame_df$tag <- 1
	
	elist_frame_df <-
		nlist_frame_df %>%
		full_join(nlist_frame_df, by = "tag") %>%
		select(-tag) %>%
		rename(node_i = node.x,
			node_j = node.y)
	
	return(elist_frame_df)
	
}





### add_eid() ###
# Aim: add edge ID to edgelist.
# Requires: complete edgelist with node IDs in first two columns (edgelist frame).
# Note: directed network not allowed in current version

add_eid <- function(elist_frame_df){
	
	tech_df1 <-
		elist_frame_df %>%
		filter(elist_frame_df[, 1] <= elist_frame_df[, 2]) %>%
		mutate(eid = seq(from = 1, to = n(), by = 1))
	
	tech_df2 <-
		tech_df1 %>%
		select(2, 1, 3)	
	
	colnames(tech_df2) <- colnames(tech_df1)
	
	elist_frame_df <-
		bind_rows(tech_df1, tech_df2) %>%
		distinct() %>%
		arrange(.[1], .[2])
	
	
	return(elist_frame_df)
	
}
```







### **Make undirected by summing the twoway SR values and dividing it by 2 (hence the Neffke-way) ("avg" approach)**

```{r, echo = FALSE}
# get frame for all industry-industry combinations with attached edge IDs
nlist_frame <- get_nlist_frame(srnet2dig)
elist_frame <- get_elist_frame(nlist_frame)
elist_frame <- add_eid(elist_frame)



#make undirected
elist2dig <-
	elist_frame %>%
  rename(ind_i = node_i, ind_j = node_j) %>%
  #Merge in SR measures to edgelist frame. Both ind_i -> ind_j, and ind_j -> ind_i gets added this way.
	left_join(srnet2dig, by = c("ind_i", "ind_j")) %>%
  #make undirected
	arrange(eid, ind_i, ind_j) %>%
	group_by(eid) %>%
	mutate(sr_norm = sum(sr_norm, na.rm = TRUE) / 2) %>%
	mutate(tag_drop = ifelse(sum(is.na(sr)) == 2, 1, 0)) %>% # handle the twoway missings here
	ungroup() %>%
	#drop if edge is not identified either way, or loop
	filter(ind_i != ind_j) %>%
	filter(tag_drop != 1) %>%
	#keep necessary variables
  select(ind_i, ind_j, eid, sr_norm)
	  



#keep edge if above threshold
srnet_nat_2dig_avg_13_19 <- elist2dig %>% filter(sr_norm > 0)
```

```{r, echo = FALSE}
# get frame for all industry-industry combinations with attached edge IDs
nlist_frame <- get_nlist_frame(srnet3dig)
elist_frame <- get_elist_frame(nlist_frame)
elist_frame <- add_eid(elist_frame)



#make undirected
elist3dig <-
	elist_frame %>%
  rename(ind_i = node_i, ind_j = node_j) %>%
  #Merge in SR measures to edgelist frame. Both ind_i -> ind_j, and ind_j -> ind_i gets added this way.
	left_join(srnet3dig, by = c("ind_i", "ind_j")) %>%
  #make undirected
	arrange(eid, ind_i, ind_j) %>%
	group_by(eid) %>%
	mutate(sr_norm = sum(sr_norm, na.rm = TRUE) / 2) %>%
	mutate(tag_drop = ifelse(sum(is.na(sr)) == 2, 1, 0)) %>% # handle the twoway missings here
	ungroup() %>%
	#drop if edge is not identified either way, or loop
	filter(ind_i != ind_j) %>%
	filter(tag_drop != 1) %>%
	#keep necessary variables
  select(ind_i, ind_j, eid, sr_norm)
	  



#keep edge if above threshold
srnet_nat_3dig_avg_13_19 <- elist3dig %>% filter(sr_norm > 0)
```

```{r, echo = FALSE}
# get frame for all industry-industry combinations with attached edge IDs
nlist_frame <- get_nlist_frame(srnet4dig)
elist_frame <- get_elist_frame(nlist_frame)
elist_frame <- add_eid(elist_frame)



#make undirected
elist4dig <-
	elist_frame %>%
  rename(ind_i = node_i, ind_j = node_j) %>%
  #Merge in SR measures to edgelist frame. Both ind_i -> ind_j, and ind_j -> ind_i gets added this way.
	left_join(srnet4dig, by = c("ind_i", "ind_j")) %>%
  #make undirected
	arrange(eid, ind_i, ind_j) %>%
	group_by(eid) %>%
	mutate(sr_norm = sum(sr_norm, na.rm = TRUE) / 2) %>%
	mutate(tag_drop = ifelse(sum(is.na(sr)) == 2, 1, 0)) %>% # handle the twoway missings here
	ungroup() %>%
	#drop if edge is not identified either way, or loop
	filter(ind_i != ind_j) %>%
	filter(tag_drop != 1) %>%
	#keep necessary variables
  select(ind_i, ind_j, eid, sr_norm)
	  



#keep edge if above threshold
srnet_nat_4dig_avg_13_19 <- elist4dig %>% filter(sr_norm > 0)
```

```{r}
#save an edgelist that is undirected and "pairwise complete" - having each edge both ways -, but no loops or edges with no information
save(srnet_nat_2dig_avg_13_19, file = "../02_data/srnet_nat_2dig_avg_13_19.RData")
write.csv(srnet_nat_2dig_avg_13_19, file = "../02_data/srnet_nat_2dig_avg_13_19.csv", row.names = FALSE)

save(srnet_nat_3dig_avg_13_19, file = "../02_data/srnet_nat_3dig_avg_13_19.RData")
write.csv(srnet_nat_3dig_avg_13_19, file = "../02_data/srnet_nat_3dig_avg_13_19.csv", row.names = FALSE)

save(srnet_nat_4dig_avg_13_19, file = "../02_data/srnet_nat_4dig_avg_13_19.RData")
write.csv(srnet_nat_4dig_avg_13_19, file = "../02_data/srnet_nat_4dig_avg_13_19.csv", row.names = FALSE)
```




# **National IO tables**

## **Hungary**

```{r}
# process raw IO data
# a dict. of names corresponding to line_id
line_names_dict <- 
  raw_io_data_hun %>%
  select(line_id, line_name) %>%
  slice(-1)


# a processed long dataset with industry numbers and labels separated
io_data_hun <-
  raw_io_data_hun %>%
  select(-line_name) %>%
  slice(-1) %>%
  rename(line_id_i = line_id) %>%
  pivot_longer(
    -line_id_i,
    names_to = "line_id_j",
    names_prefix = "line_id",
    values_to = "val"
  ) %>%
  mutate(line_id_j = as.numeric(line_id_j),
         val = as.numeric(val)) %>%
  #add industry names and codes
  left_join(line_names_dict, by = c("line_id_i" = "line_id")) %>%
  rename(line_name_i = line_name) %>%
  left_join(line_names_dict, by = c("line_id_j" = "line_id")) %>%
  rename(line_name_j = line_name) %>%
  #get real industry codes and names
  separate(line_name_i, into = c("ind_i", "indlab_i"), sep = ":") %>%
  separate(line_name_j, into = c("ind_j", "indlab_j"), sep = ":") %>%
  #cleanup
  mutate(
    ind_i = as.numeric(ind_i),
    ind_j = as.numeric(ind_j)
  ) %>%
  select(ind_i, ind_j, val, indlab_i, indlab_j)



#stash industry labels
io_hun_indlab_dict <-
  io_data_hun %>%
  select(ind_i, indlab_i) %>%
  rename(
    ind = ind_i,
    indlab = indlab_i
  ) %>%
  distinct()



#get final IO elist \wo labels
io_elist_hun <-
  io_data_hun %>%
  select(ind_i, ind_j, val)



#get IO as adjacecy matrix (still DF)
io_adjmat_hun <-
  io_elist_hun %>%
  pivot_wider(
    names_from = "ind_j",
    names_prefix = "ind_",
    values_from = "val"
  ) %>%
  rename(ind = ind_i)
```

```{r}
# save
saveRDS(io_elist_hun, file = "../02_data/io_elist_2018_hun.rds")
write.csv(io_elist_hun, file = "../02_data/io_elist_2018_hun.csv", row.names = FALSE)
```





## **Sweden**

```{r}
# process raw IO data
# a dict. of names corresponding to line_id
line_names_dict <-
  raw_io_data_swe %>%
  select(line_id, line_name) %>%
  slice(-1) %>%
  # change encoding of industry code combinations
  mutate(
    line_name = str_replace(line_name, "T", "_"),
    line_name = str_replace(line_name, "_-U", "T-U"),
    line_name = str_replace(line_name, "-", "_"),
    line_name = str_replace(line_name, "B", "B05_09"),
    line_name = str_replace(line_name, "F", "F41_43"),
    line_name = str_replace(line_name, "I", "I55_56"),
    line_name = str_replace(line_name, "T_U", "T97_U99")
  )


# a processed long dataset with industry numbers and labels separated
io_data_swe <-
  raw_io_data_swe %>%
  select(-line_name) %>%
  slice(-1) %>%
  rename(line_id_i = line_id) %>%
  pivot_longer(
    -line_id_i,
    names_to = "line_id_j",
    names_prefix = "line_id",
    values_to = "val"
  ) %>%
  mutate(
    line_id_j = as.numeric(line_id_j),
    val = as.numeric(val)
  ) %>%
  # add industry names and codes
  left_join(line_names_dict, by = c("line_id_i" = "line_id")) %>%
  rename(line_name_i = line_name) %>%
  left_join(line_names_dict, by = c("line_id_j" = "line_id")) %>%
  rename(line_name_j = line_name) %>%
  # cleanup
  rename(
    ind_i = line_name_i,
    ind_j = line_name_j
  ) %>%
  select(ind_i, ind_j, val)



# get final IO elist \wo labels
io_elist_swe <-
  io_data_swe %>%
  select(ind_i, ind_j, val)



# get IO as adjacecy matrix (still DF)
io_adjmat_swe <-
  io_elist_swe %>%
  pivot_wider(
    names_from = "ind_j",
    names_prefix = "ind_",
    values_from = "val"
  ) %>%
  rename(ind = ind_i)
```

```{r}
# save
saveRDS(io_elist_swe, file = "../02_data/io_elist_2016_swe.rds")
write.csv(io_elist_swe, file = "../02_data/io_elist_2016_swe.csv", row.names = FALSE)
```