---
title: "coagglomeration -- OC 2022-NOV"
output: html_notebook
---

developed by sandorjuhasz

### coagglomeration

3 distinct version prepared <br>
-- all 3-digit NACE industries <br>
-- only manufacturing 3-digit NACE industries <br>
-- only MNEs in all 3-digit NACE industries <br>

all 3 distinct versions are prepared for 3 region types <br>
-- megye (NUTS 3) <br>
-- jaras (LAU 1) <br>
-- urban agglomeration (20) <br>


```{r, results=FALSE, message=FALSE}
source("../scripts/02_coagglomeration_exploration_functions.R")
library(data.table)
library(dplyr)
options(dplyr.summarise.inform = FALSE)
library(mefa4)
library(ggplot2)
library(ggraph)
library(patchwork)
library(cowplot)

# parameters
region <- c("megye", "agglom", "jaras")
industry <- "nace3d"
colors <- c("#e9c46a", "#264653")
```

```{r}
# list of different data versions
coagg_data <- list()
for(v in 1:length(region))
{
  coagg_data[[v]] <- fread(
    paste0(
      "../data/oc_2022_november/coagglomeration_manufacturing_",
      industry,
      "_",
      region[v],
      "_totalemp.csv"
    )
  )
}

# plot construction
p1 <- ggplot(data.frame(coagg_data[[1]]), aes(x = coagglomeration)) +
  geom_histogram(bins=30, , color="black", fill=colors[2]) +
  ggtitle(region[1]) +
  xlab("Coagglomeration") +
  ylab("Frequency") +
  #scale_y_log10(labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  theme_cowplot(12) +
  theme(axis.text = element_text(size=10), axis.title=element_text(size=15))

p2 <- ggplot(data.frame(coagg_data[[2]]), aes(x = coagglomeration)) +
  geom_histogram(bins=30, , color="black", fill=colors[2]) +
  ggtitle(region[2]) +
  xlab("Coagglomeration") +
  ylab("Frequency") +
  #scale_y_log10(labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  theme_cowplot(12) +
  theme(axis.text = element_text(size=10), axis.title=element_text(size=15))

p3 <- ggplot(data.frame(coagg_data[[3]]), aes(x = coagglomeration)) +
  geom_histogram(bins=30, , color="black", fill=colors[2]) +
  ggtitle(region[3]) +
  xlab("Coagglomeration") +
  ylab("Frequency") +
  #scale_y_log10(labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  theme_cowplot(12) +
  theme(axis.text = element_text(size=10), axis.title=element_text(size=15))

(p1 + p2 + p3)
```

<br>
megye or urban agglomeration seems to be a better choice..<br>
<br>

### transactions

```{r}
# list of different data versions
tr_data <- list()
for(v in 1:length(region))
{
  tr_data[[v]] <- fread(
    paste0(
      "../data/oc_2022_november/transactions_indreg_",
      industry,
      "_",
      region[v],
      ".csv"
    )
  )
}

# aggregate to industry-industry level
group_cols <- c("nace3d1", "nace3d2")
indind_tr <- list()
for(t in 1:length(tr_data)){
  indind_tr[[t]] <- ind_ind_aggregation(tr_data[[t]], group_cols, weight_col = "tb_count", weight_min = 1)
}








# distribution plots

```


```{r}
# skill relatedness
```


```{r}
# scatter plots
```


```{r}
# replication - univar regressions
```


```{r}
# replication - full model
```


```{r}
# only manufacturing
```


```{r}
# only MNEs
```


```{r}
# growth -- industry-region level
```

